Path name without file-name = ./_build/html
   File name = ..
Path name without file-name = ./_build/html
   File name = genindex.html
Path name without file-name = ./_build/html
   File name = _images
Path name without file-name = ./_build/html/_images
   File name = ..
Path name without file-name = ./_build/html/_images
   File name = inorder-successor-1.jpg
Path name without file-name = ./_build/html/_images
   File name = .
Path name without file-name = ./_build/html/_images
   File name = 4-node-split-3.jpg
Path name without file-name = ./_build/html/_images
   File name = delete-barrow-1.jpg
Path name without file-name = ./_build/html/_images
   File name = heap-depiction.jpg
Path name without file-name = ./_build/html/_images
   File name = delete-fuse-1.jpg
Path name without file-name = ./_build/html/_images
   File name = heap-as-array1.gif
Path name without file-name = ./_build/html/_images
   File name = delete-barrow-2.jpg
Path name without file-name = ./_build/html/_images
   File name = 4-node-split-1.jpg
Path name without file-name = ./_build/html/_images
   File name = 4-node-root-2.gif
Path name without file-name = ./_build/html/_images
   File name = 4-node-split-2.jpg
Path name without file-name = ./_build/html/_images
   File name = binary-exp-tree.jpg
Path name without file-name = ./_build/html/_images
   File name = 4-node-root-1.jpg
Path name without file-name = ./_build/html
   File name = .
Path name without file-name = ./_build/html
   File name = search.html
Path name without file-name = ./_build/html
   File name = _static
Path name without file-name = ./_build/html/_static
   File name = doctools.js
Path name without file-name = ./_build/html/_static
   File name = ..
Path name without file-name = ./_build/html/_static
   File name = comment-close.png
Path name without file-name = ./_build/html/_static
   File name = basic.css
Path name without file-name = ./_build/html/_static
   File name = ajax-loader.gif
Path name without file-name = ./_build/html/_static
   File name = comment.png
Path name without file-name = ./_build/html/_static
   File name = documentation_options.js
Path name without file-name = ./_build/html/_static
   File name = minus.png
Path name without file-name = ./_build/html/_static
   File name = comment-bright.png
Path name without file-name = ./_build/html/_static
   File name = sphinxdoc.css
Path name without file-name = ./_build/html/_static
   File name = contents.png
Path name without file-name = ./_build/html/_static
   File name = .
Path name without file-name = ./_build/html/_static
   File name = jquery.js
Path name without file-name = ./_build/html/_static
   File name = plus.png
Path name without file-name = ./_build/html/_static
   File name = pygments.css
Path name without file-name = ./_build/html/_static
   File name = navigation.png
Path name without file-name = ./_build/html/_static
   File name = css
Path name without file-name = ./_build/html/_static/css
   File name = ..
Path name without file-name = ./_build/html/_static/css
   File name = .
Path name without file-name = ./_build/html/_static/css
   File name = kurt.css
Path name without file-name = ./_build/html/_static
   File name = up.png
Path name without file-name = ./_build/html/_static
   File name = file.png
Path name without file-name = ./_build/html/_static
   File name = searchtools.js
Path name without file-name = ./_build/html/_static
   File name = down-pressed.png
Path name without file-name = ./_build/html/_static
   File name = websupport.js
Path name without file-name = ./_build/html/_static
   File name = underscore.js
Path name without file-name = ./_build/html/_static
   File name = down.png
Path name without file-name = ./_build/html/_static
   File name = language_data.js
Path name without file-name = ./_build/html/_static
   File name = up-pressed.png
Path name without file-name = ./_build/html
   File name = .buildinfo
Path name without file-name = ./_build/html
   File name = todo.html
Path name without file-name = ./_build/html
   File name = objects.inv
Path name without file-name = ./_build/html
   File name = notes
Path name without file-name = ./_build/html/notes
   File name = heap.html
Path name without file-name = ./_build/html/notes
   File name = ..
Path name without file-name = ./_build/html/notes
   File name = hashtable.html
Path name without file-name = ./_build/html/notes
   File name = radix-sort.html
Path name without file-name = ./_build/html/notes
   File name = tree-implementations.html
Path name without file-name = ./_build/html/notes
   File name = merge-sort.html
Path name without file-name = ./_build/html/notes
   File name = shell-sort.html
Path name without file-name = ./_build/html/notes
   File name = stack.html
Path name without file-name = ./_build/html/notes
   File name = tree234.html
Path name without file-name = ./_build/html/notes
   File name = .
Path name without file-name = ./_build/html/notes
   File name = tree23.html
Path name without file-name = ./_build/html/notes
   File name = pivotsort.html
Path name without file-name = ./_build/html/notes
   File name = bst.html
Path name without file-name = ./_build/html/notes
   File name = avl-tree.html
Path name without file-name = ./_build/html/notes
   File name = llrb.html
Path name without file-name = ./_build/html/notes
   File name = rb-tree.html
Path name without file-name = ./_build/html/notes
   File name = union-find.html
Path name without file-name = ./_build/html/notes
   File name = visualizations.html
Path name without file-name = ./_build/html/notes
   File name = tree-iterative-traversal.html
Path name without file-name = ./_build/html
   File name = index.html
Path name without file-name = ./_build/html
   File name = _sources
Path name without file-name = ./_build/html/_sources
   File name = ..
Path name without file-name = ./_build/html/_sources
   File name = index.rst.txt
Path name without file-name = ./_build/html/_sources
   File name = todo.rst.txt
Path name without file-name = ./_build/html/_sources
   File name = .
Path name without file-name = ./_build/html/_sources
   File name = notes
Path name without file-name = ./_build/html/_sources/notes
   File name = ..
Path name without file-name = ./_build/html/_sources/notes
   File name = visualizations.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = shell-sort.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = avl-tree.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = heap.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = .
Path name without file-name = ./_build/html/_sources/notes
   File name = merge-sort.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = tree-iterative-traversal.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = union-find.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = tree234.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = tree-implementations.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = tree23.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = hashtable.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = llrb.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = rb-tree.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = bst.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = stack.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = radix-sort.rst.txt
Path name without file-name = ./_build/html/_sources/notes
   File name = pivotsort.rst.txt
Path name without file-name = ./_build/html
   File name = searchindex.js
