In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
Path name without file-name = ./_build/html
   File name = genindex.html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
Path name without file-name = ./_build/html
   File name = search.html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
Path name without file-name = ./_build/html
   File name = todo.html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
Path name without file-name = ./_build/html
   File name = index.html
In accept() getPath() = ./_build/html
In accept() getPath() = ./_build/html
